"""add_soft_delete_and_image_urls

Revision ID: 7a8e37b4ad48
Revises: a5839014aa66
Create Date: 2026-05-24 14:33:40.689614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8e37b4ad48'
down_revision: Union[str, Sequence[str], None] = 'a5839014aa66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('image_url', sa.String(length=512), nullable=True))
    op.add_column('attendance_records', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('employees', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('face_embeddings', sa.Column('image_url', sa.String(length=512), nullable=True))
    op.add_column('face_embeddings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face_embeddings', 'deleted_at')
    op.drop_column('face_embeddings', 'image_url')
    op.drop_column('employees', 'deleted_at')
    op.drop_column('attendance_records', 'deleted_at')
    op.drop_column('attendance_records', 'image_url')
    # ### end Alembic commands ###
