"""Add work_date to AttendanceRecord

Revision ID: a5839014aa66
Revises: 1b969b30a849
Create Date: 2026-05-20 16:06:50.349145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5839014aa66"
down_revision: Union[str, Sequence[str], None] = "1b969b30a849"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attendance_records", sa.Column("work_date", sa.Date(), nullable=False)
    )
    op.create_index(
        op.f("ix_attendance_records_work_date"),
        "attendance_records",
        ["work_date"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_attendance_employee_date",
        "attendance_records",
        ["employee_id", "work_date"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_attendance_employee_date", "attendance_records", type_="unique"
    )
    op.drop_index(
        op.f("ix_attendance_records_work_date"), table_name="attendance_records"
    )
    op.drop_column("attendance_records", "work_date")
    # ### end Alembic commands ###
